// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Issues", testIssuesUpsert)

	t.Run("Projectcards", testProjectcardsUpsert)

	t.Run("Projects", testProjectsUpsert)

	t.Run("Pullrequests", testPullrequestsUpsert)

	t.Run("Repositories", testRepositoriesUpsert)

	t.Run("Users", testUsersUpsert)
}
